add must use annotation to functions that have no mutable args or statics
Malax/libcnb.rs pull request #145
Opened 2021-11-11 20:23 UTC by lillianzhang331

https://rust-lang.github.io/rust-clippy/master/index.html#must_use_candidate
Fixes #57

2021-11-12 10:40 UTC, Malax approved these changes

2021-11-12 10:59 UTC, Malax requested changes
After discussing this PR with @edmorley, I remove my approve. Adding `must_use` makes sense, but we need to go further than just slapping annotations on anything where static analysis can figure out the value needs to be used.

We most likely want to add messages to most of them too.

2021-11-15 10:18 UTC, edmorley commented on libcnb/src/build.rs
> +    #[must_use]
I don't think `#[must_use]` should be used on this function and the one below given they do mutate the original struct - seems like false positives.

Fixing this lint is definitely one where we need to vet each case and not just add the annotations where clippy suggested without checking :-)

2021-11-15 10:36 UTC, edmorley commented
I found some guidelines on when to use `must_use`, here:
https://github.com/rust-lang/rust/issues/48926#issuecomment-769286972

2021-11-17 17:47 UTC, Malax commented
Should we close this PR and continue discussion in the issue itself, or create a new one? This PR will not be merged anytime soon and with a very different changeset, correct?

2021-11-17 17:52 UTC, edmorley commented
I think we should close this for now, and discuss in the issue what strategy we wish to use here before opening a new PR.

2021-11-17 18:39 UTC, closed without merging