add Errors documentation
Malax/libcnb.rs pull request #213
Opened 2021-11-29 22:23 UTC by lillianzhang331

Fixes #53 
We need to add an "Errors section to document the types of errors that can be returned from a function. This will help developers write code to handle the errors properly.

https://rust-lang.github.io/rust-clippy/master/index.html#missing_errors_doc
https://rust-lang.github.io/api-guidelines/documentation.html#function-docs-include-error-panic-and-safety-considerations-c-failure

2021-11-30 10:36 UTC, edmorley requested changes
Thank you for working on this!

On [the upstream api guideline docs](https://rust-lang.github.io/api-guidelines/documentation.html#function-docs-include-error-panic-and-safety-considerations-c-failure), they give an example of:

```rust
/// # Errors
///
/// If this function encounters any form of I/O or other error, an error
/// variant will be returned. If an error is returned then it must be
/// guaranteed that no bytes were read.
```

This wording focuses more on the reasons an error can occur, and any caveats around that (eg the guarantees about bytes read).

Looking at the docs added here, it seems they mostly repeat the error type that can be seen in the function signature, which is something that already appears in the docs.

My first thought was that perhaps we can adjust the wordings to focus on the reasons/caveats like the example above, however going through the errors returned by libcnb's public API, it seems most are "returns an error if the buildpack returns an error" (due to libcnb being a framework designed to wrap user-created things). There are also not really any caveats (like the bytes read thing in the example) that need to be documented either.

As such, Manuel and I were thinking we should instead:
- drop the docs changes from this PR
- and then permanently disable this rule. ie: Move the rule up a few lines in `libcnb/src/lib.rs` and `libcnb-data/src/lib.rs`, so it's no longer in the "to triage" section, and then add a reason like:
   ```rust
   // Most of libcnb's public API returns user-provided errors, making error docs redundant.
   ```

Sorry this one has ended up being one we don't want to fix -- when enabling lints in an existing codebase, a hard part of that is triaging which lints are useful vs not, and sometimes that can only be determined once the changes can be seen in situ.

2021-12-01 13:10 UTC, Malax commented
As discussed in person, I'll close this @lillianzhang331.

2021-12-03 22:05 UTC, edmorley commented
> we should instead:
> 
> * drop the docs changes from this PR
> * and then permanently disable this rule. ie: Move the rule up a few lines in `libcnb/src/lib.rs` and `libcnb-data/src/lib.rs`, so it's no longer in the "to triage" section, and then add a reason like

2021-12-03 22:20 UTC, edmorley approved these changes

2021-12-03 22:20 UTC, merged